
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FitnessApplication
{

using System;
    using System.Collections.ObjectModel;
    
public partial class Account
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Account()
    {

        this.Accounts_Notification = new ObservableCollection<Accounts_Notification>();

        this.Accounts_Reminder = new ObservableCollection<Accounts_Reminder>();

        this.Accounts_Friends = new ObservableCollection<Accounts_Friends>();

        this.Accounts_Meals = new ObservableCollection<Accounts_Meals>();

        this.Accounts_Recipes = new ObservableCollection<Accounts_Recipes>();

        this.Accounts_Cardio = new ObservableCollection<Accounts_Cardio>();

        this.Accounts_Strength = new ObservableCollection<Accounts_Strength>();

    }


    public int id_Account { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public System.DateTime BirthDate { get; set; }

    public int Age { get; set; }

    public double Height { get; set; }

    public string Email { get; set; }

    public string Gender { get; set; }

    public byte[] Photo { get; set; }

    public string Username { get; set; }

    public int id_Account_Diary { get; set; }

    public int id_Account_Goals { get; set; }

    public int id_Account_AccountCredentials { get; set; }

    public int id_Account_Progress { get; set; }



    public virtual AccountCredential AccountCredential { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ObservableCollection<Accounts_Notification> Accounts_Notification { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ObservableCollection<Accounts_Reminder> Accounts_Reminder { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ObservableCollection<Accounts_Friends> Accounts_Friends { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ObservableCollection<Accounts_Meals> Accounts_Meals { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ObservableCollection<Accounts_Recipes> Accounts_Recipes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ObservableCollection<Accounts_Cardio> Accounts_Cardio { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ObservableCollection<Accounts_Strength> Accounts_Strength { get; set; }

    public virtual Diary Diary { get; set; }

    public virtual Goal Goal { get; set; }

    public virtual Progress Progress { get; set; }

}

}
