
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FitnessApplication
{

using System;
    using System.Collections.ObjectModel;
    
public partial class Cardio
{

    public int id_Cardio { get; set; }

    public string Cardio_Description { get; set; }

    public Nullable<int> Duration_min { get; set; }

    public Nullable<int> Calories_burned { get; set; }

}

}
