//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyFitEntities : DbContext
    {
        public MyFitEntities()
            : base("name=MyFitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountCredential> AccountCredentials { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Accounts_Cardio> Accounts_Cardio { get; set; }
        public virtual DbSet<Accounts_Friends> Accounts_Friends { get; set; }
        public virtual DbSet<Accounts_Meals> Accounts_Meals { get; set; }
        public virtual DbSet<Accounts_Notification> Accounts_Notification { get; set; }
        public virtual DbSet<Accounts_Recipes> Accounts_Recipes { get; set; }
        public virtual DbSet<Accounts_Reminder> Accounts_Reminder { get; set; }
        public virtual DbSet<Accounts_Strength> Accounts_Strength { get; set; }
        public virtual DbSet<BreakfastGoal> BreakfastGoals { get; set; }
        public virtual DbSet<Cardio> Cardios { get; set; }
        public virtual DbSet<Diary> Diaries { get; set; }
        public virtual DbSet<DiaryBreakfast> DiaryBreakfasts { get; set; }
        public virtual DbSet<DiaryCardio> DiaryCardios { get; set; }
        public virtual DbSet<DiaryDinner> DiaryDinners { get; set; }
        public virtual DbSet<DiaryEntry> DiaryEntries { get; set; }
        public virtual DbSet<DiaryLunch> DiaryLunches { get; set; }
        public virtual DbSet<DiaryNote> DiaryNotes { get; set; }
        public virtual DbSet<DiarySnack1> DiarySnack1 { get; set; }
        public virtual DbSet<DiarySnack2> DiarySnack2 { get; set; }
        public virtual DbSet<DiaryStrength> DiaryStrengths { get; set; }
        public virtual DbSet<DiaryWater> DiaryWaters { get; set; }
        public virtual DbSet<DinnerGoal> DinnerGoals { get; set; }
        public virtual DbSet<FitnessGoal> FitnessGoals { get; set; }
        public virtual DbSet<FriendMessage> FriendMessages { get; set; }
        public virtual DbSet<FriendRequest> FriendRequests { get; set; }
        public virtual DbSet<Friend> Friends { get; set; }
        public virtual DbSet<Goal> Goals { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<LunchGoal> LunchGoals { get; set; }
        public virtual DbSet<MealGoal> MealGoals { get; set; }
        public virtual DbSet<MyCardio> MyCardios { get; set; }
        public virtual DbSet<MyMeal> MyMeals { get; set; }
        public virtual DbSet<MyRecipe> MyRecipes { get; set; }
        public virtual DbSet<MyStrength> MyStrengths { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NutritionGoal> NutritionGoals { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Progress> Progresses { get; set; }
        public virtual DbSet<Reminder> Reminders { get; set; }
        public virtual DbSet<Snack1Goals> Snack1Goals { get; set; }
        public virtual DbSet<Snack2Goals> Snack2Goals { get; set; }
        public virtual DbSet<Strength> Strengths { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<WeightGoal> WeightGoals { get; set; }
    }
}
