//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessApplication
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class FitnessGoal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FitnessGoal()
        {
            this.Goals = new ObservableCollection<Goal>();
        }
    
        public int id_FitnessGoals { get; set; }
        public Nullable<int> WorkoutsPerWeek { get; set; }
        public Nullable<int> MinutesPerWorkout { get; set; }
        public Nullable<int> CaloriesPerWorkout { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Goal> Goals { get; set; }
    }
}
