
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FitnessApplication
{

using System;
    using System.Collections.ObjectModel;
    
public partial class FriendMessage
{

    public int id_FriendMessage { get; set; }

    public string fromUsername { get; set; }

    public string toUsername { get; set; }

    public string Message { get; set; }

}

}
