
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FitnessApplication
{

using System;
    using System.Collections.ObjectModel;
    
public partial class MealGoal
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MealGoal()
    {

        this.NutritionGoals = new ObservableCollection<NutritionGoal>();

    }


    public int id_MealGoals { get; set; }

    public Nullable<int> id_BreakfastG_MealG { get; set; }

    public Nullable<int> id_Snack1G_MealG { get; set; }

    public Nullable<int> id_LunchG_MealG { get; set; }

    public Nullable<int> id_Snack2G_MealG { get; set; }

    public Nullable<int> id_DinnerG_MealG { get; set; }



    public virtual BreakfastGoal BreakfastGoal { get; set; }

    public virtual DinnerGoal DinnerGoal { get; set; }

    public virtual LunchGoal LunchGoal { get; set; }

    public virtual Snack1Goals Snack1Goals { get; set; }

    public virtual Snack2Goals Snack2Goals { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ObservableCollection<NutritionGoal> NutritionGoals { get; set; }

}

}
