
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FitnessApplication
{

using System;
    using System.Collections.ObjectModel;
    
public partial class NutritionGoal
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NutritionGoal()
    {

        this.Goals = new ObservableCollection<Goal>();

    }


    public int id_NutritionGoals { get; set; }

    public Nullable<int> id_NutritionG_MealG { get; set; }

    public Nullable<double> CaloriesPerDay { get; set; }

    public Nullable<double> CarbsPerDay { get; set; }

    public Nullable<double> ProteinPerDay { get; set; }

    public Nullable<double> FatPerDay { get; set; }

    public Nullable<double> CholesterolPerDay { get; set; }

    public Nullable<double> SodiumPerDay { get; set; }

    public Nullable<double> PotassiumPerDay { get; set; }

    public Nullable<double> FiberPerDay { get; set; }

    public Nullable<double> SugarsPerDay { get; set; }

    public Nullable<double> VitAPerDay { get; set; }

    public Nullable<double> VitCPerDay { get; set; }

    public Nullable<double> CalciumPerDay { get; set; }

    public Nullable<double> IronPerDay { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ObservableCollection<Goal> Goals { get; set; }

    public virtual MealGoal MealGoal { get; set; }

}

}
