
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FitnessApplication
{

using System;
    using System.Collections.ObjectModel;
    
public partial class Post
{

    public int id_Post { get; set; }

    public Nullable<int> FromId { get; set; }

    public Nullable<System.DateTime> PostDate { get; set; }

    public string Content { get; set; }

    public byte[] Photo { get; set; }

}

}
