//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessApplication
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Progress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Progress()
        {
            this.Accounts = new ObservableCollection<Account>();
        }
    
        public int id_Progress { get; set; }
        public Nullable<System.DateTime> pDate { get; set; }
        public Nullable<double> pWeight { get; set; }
        public Nullable<double> pWaist { get; set; }
        public Nullable<double> pHips { get; set; }
        public Nullable<double> pLegs { get; set; }
        public Nullable<double> pBut { get; set; }
        public byte[] pPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Account> Accounts { get; set; }
    }
}
