//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessApplication
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class WeightGoal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeightGoal()
        {
            this.Goals = new ObservableCollection<Goal>();
        }
    
        public int id_WeightGoals { get; set; }
        public Nullable<double> StartingWeight { get; set; }
        public Nullable<double> CurrentWeight { get; set; }
        public Nullable<double> GoalWeight { get; set; }
        public Nullable<double> WeeklyGoal { get; set; }
        public Nullable<int> ActivityLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Goal> Goals { get; set; }
    }
}
